# SPDX-License-Identifier: AGPL-3.0-only
"""Axis declarations, and the cells generated from them.

CHARTER § 3: a cell is one point in a declared matrix, *generated* rather than
written, so the matrix's coverage is a property of the declaration and not of
anyone's memory.  `generated/` is in .gitignore for the same reason: a cell that
can be edited by hand is a cell that will be, and then the declaration stops
being the truth.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass
from pathlib import Path

from .engines import ROOT

AXES_DIR = ROOT / "axes"
GEN_DIR = ROOT / "generated"

BANNER = (
    "// GENERATED by zyddt gen from axes/{axis}.toml — do not edit.\n"
    "// axis: {axis_what}\n"
    "// cell: {cell_id} — {cell_what}\n"
)


@dataclass(frozen=True)
class Cell:
    axis: str
    id: str
    what: str
    src: str
    skip: str | None = None      # a skipped cell names what it skips, and why
    oracle: tuple[str, str] | None = None   # (oracle id, source)
    expect: str | None = None    # overrides the axis's, for one cell

    @property
    def path(self) -> Path:
        return GEN_DIR / self.axis / f"{self.id}.zy"

    def oracle_path(self, ext: str) -> Path:
        return GEN_DIR / self.axis / f"{self.id}.oracle{ext}"


@dataclass(frozen=True)
class Axis:
    id: str
    what: str
    engines: list[str]
    expect: str | None
    cells: list[Cell]


def load_all(only: list[str] | None = None) -> list[Axis]:
    out = []
    for path in sorted(AXES_DIR.glob("*.toml")):
        if only and path.stem not in only:
            continue
        d = tomllib.loads(path.read_text(encoding="utf-8"))
        axis_id = d.get("id", path.stem)
        out.append(Axis(
            id=axis_id,
            what=d.get("what", ""),
            engines=d.get("engines", []),
            expect=d.get("expect"),
            cells=[Cell(path.stem, c["id"], c.get("what", ""),
                        c["src"], c.get("skip"), _oracle_of(c, path),
                        c.get("expect"))
                   for c in d.get("cell", [])],
        ))
    return out


def _oracle_of(cell: dict, path: Path) -> tuple[str, str] | None:
    """`oracle.py = \"\"\"...\"\"\"` — at most one, because two oracles that
    disagree is a question about the oracles, not about Zymbol."""
    o = cell.get("oracle")
    if not o:
        return None
    if len(o) != 1:
        raise SystemExit(
            f"zyddt: {path.name}: cell '{cell['id']}' declares {len(o)} oracles. "
            f"One case, one independent answer.")
    return next(iter(o.items()))


def generate(axes: list[Axis], oracles: dict | None = None) -> list[Cell]:
    """Write every cell, and delete any .zy the declaration no longer produces.

    The deletion half is not tidiness.  A generated file that outlives its
    declaration is a test nobody can trace to an axis — which is precisely the
    provenance-organised corpus ZyDDT exists to stop being.
    """
    written: list[Cell] = []
    for axis in axes:
        d = GEN_DIR / axis.cells[0].axis if axis.cells else None
        keep = set()
        for cell in axis.cells:
            cell.path.parent.mkdir(parents=True, exist_ok=True)
            banner = BANNER.format(axis=cell.axis, axis_what=axis.what,
                                   cell_id=cell.id, cell_what=cell.what)
            cell.path.write_text(banner + cell.src.lstrip("\n"), encoding="utf-8")
            keep.add(cell.path.name)
            if cell.oracle and oracles:
                oid, osrc = cell.oracle
                if oid not in oracles:
                    raise SystemExit(f"zyddt: cell '{cell.axis}/{cell.id}' names "
                                     f"oracle '{oid}', which engines.toml does not "
                                     f"declare")
                op = cell.oracle_path(oracles[oid].ext)
                op.write_text(osrc.lstrip("\n"), encoding="utf-8")
                keep.add(op.name)
            written.append(cell)
        if d and d.exists():
            for stale in list(d.glob("*.zy")) + list(d.glob("*.oracle.*")):
                if stale.name not in keep:
                    stale.unlink()
    return written
